#version: '3.9'
services:
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - /home/ael/Desktop/Project_Pro/Database:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

# volumes:
#   postgres_data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ./Database