import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(
    { children }: { children: ReactNode }) {
    return (
        <html lang="en">
            <body className={cn(inter.className, "antialiased min-h-screen bg-black")}>
                <ThemeProvider>
                    <div className="absolute top-2 right-2 z-50">
                        <ThemeSwitcher />
                    </div>
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
